name = "geostar-dashboard"
main = "index.ts"
compatibility_date = "2025-01-17"
compatibility_flags = ["nodejs_compat"]
account_id = "ebb822c9645a8923b6fe123f2c2fb402"

[[d1_databases]]
binding = "GEOSTAR_DB"
database_name = "geostar"
database_id = "2734fb86-f379-48cf-b226-68e8e07dc5b9"

[observability]
enabled = true
head_sampling_rate = 1
